version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dp
      POSTGRES_PASSWORD: dp
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dp@techngem.com
      PGADMIN_DEFAULT_PASSWORD: dp
      PGADMIN_CONFIG_SERVER_MODE: "False"
    networks:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin: